-- ============================================================
-- 业务域：风格与风格市场
-- 表数量：5
-- ============================================================
SET NAMES utf8mb4;

CREATE TABLE `u_user_skill` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `biz_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务唯一编号，对外暴露',
  `user_id` bigint unsigned NOT NULL COMMENT '所属用户ID',
  `skill_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风格名称；全局唯一（按是否删除分区）',
  `prompt` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风格提示词，写入生成请求',
  `prompt_extra` json DEFAULT NULL COMMENT '结构化提示词 JSON（templateBased/role/audience/requirements/tone/restrictions）',
  `excerpt1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原文提示词示例片段1',
  `excerpt2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原文提示词示例片段2',
  `description` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '简短描述（系统预选用）',
  `prompt_summary` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示词摘要，UI 卡片展示用',
  `scope` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '适用范围标签，逗号分隔',
  `enable_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '启用状态：0-禁用，1-启用（仅系统预设有意义）',
  `source_type` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '来源类型：1-自定义，2-学习，3-系统预设',
  `use_count` int unsigned NOT NULL DEFAULT '0' COMMENT '累计使用次数',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `audit_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '审核状态：0-待审核，1-已通过，2-已拒绝',
  `audited_by` bigint unsigned DEFAULT NULL COMMENT '审核管理员ID',
  `audited_at` datetime(3) DEFAULT NULL COMMENT '审核时间',
  `reject_reason` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '打回原因',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_u_user_style_biz_no` (`biz_no`),
  UNIQUE KEY `uk_u_user_skill_skill_name_deleted` (`skill_name`,`is_deleted`),
  KEY `idx_u_user_style_user_id_source` (`user_id`,`source_type`),
  KEY `idx_u_user_style_audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `u_user_style` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `biz_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务唯一编号，对外暴露',
  `user_id` bigint unsigned NOT NULL COMMENT '所属用户ID',
  `style_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风格名称',
  `prompt` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风格提示词，写入生成请求',
  `description` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '简短描述（系统预选用）',
  `prompt_summary` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示词摘要，UI 卡片展示用',
  `scope` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '适用范围标签，逗号分隔',
  `enable_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '启用状态：0-禁用，1-启用（仅系统预设有意义）',
  `source_type` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '来源类型：1-自定义，2-学习，3-系统预设',
  `use_count` int unsigned NOT NULL DEFAULT '0' COMMENT '累计使用次数',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `audit_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '审核状态：0-待审核，1-已通过，2-已拒绝',
  `audited_by` bigint unsigned DEFAULT NULL COMMENT '审核管理员ID',
  `audited_at` datetime(3) DEFAULT NULL COMMENT '审核时间',
  `reject_reason` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '打回原因',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_u_user_style_biz_no` (`biz_no`),
  UNIQUE KEY `uk_u_user_style_user_id_name` (`user_id`,`style_name`),
  KEY `idx_u_user_style_user_id_source` (`user_id`,`source_type`),
  KEY `idx_u_user_style_audit_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `u_skill_market` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `biz_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务唯一编号，对外暴露',
  `skill_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风格名称',
  `description` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '简短描述',
  `prompt_summary` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示词摘要，UI 卡片展示用',
  `prompt` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '完整风格提示词',
  `scope` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '适用范围标签，逗号分隔',
  `publisher_user_id` bigint unsigned NOT NULL COMMENT '发布者用户ID（u_user.id）',
  `price` decimal(10,2) NOT NULL DEFAULT '0.20' COMMENT '单次使用价格（创作币），本期固定 0.2',
  `total_uses` int unsigned NOT NULL DEFAULT '0' COMMENT '累计使用次数（管理端可维护）',
  `weekly_uses` int unsigned NOT NULL DEFAULT '0' COMMENT '本周使用次数（结算用，本期只读）',
  `weekly_earnings` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '本周基础收益（本期只读）',
  `milestone_bonus` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '本周已发放里程碑奖励（本期只读）',
  `last_settlement_at` datetime(3) DEFAULT NULL COMMENT '上次结算时间（本期只读）',
  `enable_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '启用状态：0-禁用，1-启用',
  `featured` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否官方精选：0-否，1-是',
  `audit_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '审核状态：0-待审核，1-已通过，2-已拒绝',
  `approved_at` datetime(3) DEFAULT NULL COMMENT '审核通过时间',
  `source_type` tinyint unsigned NOT NULL DEFAULT '3' COMMENT '来源：1-用户自定义，2-学习风格，3-平台运营',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_skill_market_biz_no` (`biz_no`),
  KEY `idx_skill_market_publisher` (`publisher_user_id`),
  KEY `idx_skill_market_enable_deleted` (`enable_status`,`is_deleted`),
  KEY `idx_skill_market_audit` (`audit_status`),
  KEY `idx_skill_market_name` (`skill_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `u_style_market` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `biz_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务唯一编号，对外暴露',
  `style_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风格名称',
  `description` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '简短描述',
  `prompt_summary` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示词摘要，UI 卡片展示用',
  `prompt` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '完整风格提示词',
  `scope` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '适用范围标签，逗号分隔',
  `publisher_user_id` bigint unsigned NOT NULL COMMENT '发布者用户ID（u_user.id）',
  `price` decimal(10,2) NOT NULL DEFAULT '2.00' COMMENT '单次使用价格（创作币），本期固定 2',
  `total_uses` int unsigned NOT NULL DEFAULT '0' COMMENT '累计使用次数（管理端可维护）',
  `weekly_uses` int unsigned NOT NULL DEFAULT '0' COMMENT '本周使用次数（结算用，本期只读）',
  `weekly_earnings` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '本周基础收益（本期只读）',
  `milestone_bonus` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '本周已发放里程碑奖励（本期只读）',
  `last_settlement_at` datetime(3) DEFAULT NULL COMMENT '上次结算时间（本期只读）',
  `enable_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '启用状态：0-禁用，1-启用',
  `audit_status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '审核状态：0-待审核，1-已通过，2-已拒绝',
  `source_type` tinyint unsigned NOT NULL DEFAULT '3' COMMENT '来源：1-用户自定义，2-学习风格，3-平台运营',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `created_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '创建人ID',
  `updated_by` bigint unsigned NOT NULL DEFAULT '0' COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_style_market_biz_no` (`biz_no`),
  KEY `idx_style_market_publisher` (`publisher_user_id`),
  KEY `idx_style_market_enable_deleted` (`enable_status`,`is_deleted`),
  KEY `idx_style_market_audit` (`audit_status`),
  KEY `idx_style_market_name` (`style_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `u_user_market_favorite` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `market_skill_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '市场 skill 业务编号',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '收藏时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_u_user_market_favorite` (`user_id`,`market_skill_id`),
  KEY `idx_u_user_market_favorite_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
