SET NAMES utf8mb4;

-- ============================================================
-- 2026-08-28: 基于 12 套参考 DOCX 风格二次优化导出模板
--   1) 补充 headingTextShadow 参数
--   2) 重写 30 个模板 visual_style_json，让配色、标题、小标题、
--      引用块更贴近参考风格（中古/北欧/复古/新中式/法式/工业/波普/
--      律动/马卡龙/科技蓝/赛博朋克等）
-- ============================================================

-- 1) 补充新参数（已存在则忽略）
INSERT IGNORE INTO a_export_template_param (param_key, display_label, field_type, group_label, default_value, options_json, sort_order) VALUES
    ('headingTextShadow', '小标题文字阴影', 'text', '小标题', NULL, NULL, 155);

-- 2) 更新 30 个模板视觉样式
UPDATE a_export_template SET visual_style_json = '{"bg":"#f8fbfa","font":"-apple-system, BlinkMacSystemFont, \\"Segoe UI\\", sans-serif","titleColor":"#1a1a1a","titleSize":"24px","titleFontWeight":700,"titleLetterSpacing":"-0.01em","titleLineHeight":1.35,"metaColor":"#527a6b","metaBorder":"#d9e8e0","bodyColor":"#2d3436","bodySize":"15px","bodyLine":1.85,"headingColor":"#52b788","headingSize":"17px","headingFontWeight":700,"headingBorder":"4px solid #52b788","headingPl":10,"calloutBg":"#f0faf4","calloutBorder":"4px solid #52b788","calloutColor":"#2d3436"}' WHERE template_key = 'wechat';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#fff","titleSize":"24px","titleFontWeight":800,"titleBackground":"#2b7ae8","titlePadding":"14px 18px","titleBorderRadius":"8px","titleTextShadow":"0 1px 2px rgba(0,0,0,0.15)","metaColor":"#2b7ae8","metaBorder":"#d6e8f7","metaBackground":"#f0f7ff","metaPadding":"4px 12px","metaBorderRadius":"999px","bodyColor":"#1a1a2e","bodySize":"14px","bodyLine":1.85,"headingColor":"#2b7ae8","headingSize":"16px","headingFontWeight":700,"headingBorder":"3px solid #2b7ae8","headingPl":10,"headingBackground":"#f0f7ff","headingPadding":"6px 12px","headingBorderRadius":"4px","calloutBg":"#f0f7ff","calloutBorder":"3px solid #2b7ae8","calloutColor":"#1a1a2e"}' WHERE template_key = 'business';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff9f5","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#e17055","titleSize":"26px","titleFontWeight":900,"titleLetterSpacing":"0.02em","titleBackground":"linear-gradient(135deg, #fff 0%, #ffefe6 100%)","titlePadding":"16px","titleBorderRadius":"12px","titleBorder":"2px solid #fab1a0","metaColor":"#e17055","metaBorder":"#fab1a0","metaBackground":"#fff0e8","metaPadding":"4px 12px","metaBorderRadius":"999px","bodyColor":"#2d3436","bodySize":"15px","bodyLine":1.85,"headingColor":"#e17055","headingSize":"17px","headingFontWeight":700,"headingBorderBottom":"2px solid #fab1a0","calloutVariant":"cta","calloutBg":"#fff","calloutColor":"#e17055","calloutBorderRadius":"8px","calloutShadow":"0 2px 8px rgba(225,112,85,0.12)"}' WHERE template_key = 'marketing';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fdf8f3","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#3d3229","titleSize":"24px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":400,"titleLetterSpacing":"0.02em","titleAlign":"center","titleFontStyle":"italic","titleBorderBottom":"2px solid #d4a373","titleMarginBottom":"20px","metaColor":"#7d7067","metaBorder":"#e8dccb","metaAlign":"center","bodyColor":"#3d3229","bodySize":"14px","bodyLine":1.95,"bodyAlign":"justify","headingColor":"#b85c38","headingSize":"16px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingFontWeight":700,"headingBorderBottom":"1px solid #d4a373","headingTextTransform":"uppercase","headingLetterSpacing":"0.08em","calloutBg":"#f5ebe0","calloutBorder":"none","calloutColor":"#7d7067","calloutBorderRadius":"6px"}' WHERE template_key = 'academic';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f5f5f5","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1a1a1a","titleSize":"26px","titleFontWeight":900,"titleBorderBottom":"4px solid #984807","titleMarginBottom":"16px","metaColor":"#7f8c8d","metaBorder":"#d9d9d9","bodyColor":"#4a4a4a","bodySize":"15px","bodyLine":1.9,"headingColor":"#984807","headingSize":"17px","headingFontWeight":800,"headingBorder":"4px solid #984807","headingPl":10,"headingTextTransform":"uppercase","headingLetterSpacing":"0.04em","calloutBg":"#f0f0f0","calloutBorder":"3px solid #984807","calloutColor":"#4a4a4a"}' WHERE template_key = 'toutiao';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#5b8c85","titleSize":"24px","titleFontWeight":800,"titleIcon":"✿","titleBackground":"#f4f6f6","titlePadding":"12px 18px","titleBorderRadius":"16px","titleBorder":"1px solid #e0e8e6","metaColor":"#7aafa5","metaBorder":"#e0e8e6","metaBackground":"#f4f6f6","metaPadding":"4px 12px","metaBorderRadius":"999px","bodyColor":"#4a5568","bodySize":"14px","bodyLine":1.8,"headingColor":"#5b8c85","headingSize":"15px","headingFontWeight":700,"headingBorderBottom":"2px solid #f4a6b3","calloutVariant":"pill","calloutBg":"#fff5f7","calloutColor":"#f4a6b3"}' WHERE template_key = 'xiaohongshu';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1a1a2e","titleSize":"24px","titleFontWeight":800,"titleIcon":"💡","titleBackground":"#f0f7ff","titlePadding":"12px 18px","titleBorderRadius":"10px 0 10px 0","titleBorder":"1px solid #d6e8f7","metaColor":"#4a5568","metaBorder":"#d6e8f7","metaBackground":"#f0f7ff","metaPadding":"4px 10px","metaBorderRadius":"4px","bodyColor":"#1a1a2e","bodySize":"14px","bodyLine":1.85,"headingColor":"#2b7ae8","headingSize":"16px","headingFontWeight":700,"headingBorder":"4px solid #2b7ae8","headingPl":10,"calloutVariant":"card","calloutBg":"#fff","calloutColor":"#2b7ae8","calloutBorderRadius":"8px","calloutShadow":"0 2px 8px rgba(43,122,232,0.08)"}' WHERE template_key = 'baijiahao';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f5f5f0","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#1b4332","titleSize":"24px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":400,"titleFontStyle":"italic","titleBorderBottom":"2px solid #d4a574","titleMarginBottom":"20px","metaColor":"#52796f","metaBorder":"#d4a574","metaAlign":"center","bodyColor":"#1b4332","bodySize":"15px","bodyLine":1.95,"headingColor":"#52796f","headingSize":"16px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingFontWeight":700,"headingBorderBottom":"1px solid #d4a574","calloutBg":"#e8f0e8","calloutBorder":"3px solid #52796f","calloutColor":"#1b4332"}' WHERE template_key = 'story';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#1f2937","titleSize":"28px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":400,"titleAlign":"center","titleLetterSpacing":"0.04em","titleBorderBottom":"1px solid #e5e7eb","titleMarginBottom":"20px","metaColor":"#6b7280","metaBorder":"#e5e7eb","metaAlign":"center","bodyColor":"#374151","bodySize":"14px","bodyLine":1.95,"bodyAlign":"justify","headingColor":"#e94560","headingSize":"17px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingAlign":"center","headingFontWeight":700,"headingBorderBottom":"1px solid #e5e7eb","headingTextTransform":"uppercase","headingLetterSpacing":"0.06em","calloutBg":"#fef2f3","calloutBorder":"none","calloutColor":"#e94560","calloutBorderRadius":"6px","calloutShadow":"none"}' WHERE template_key = 'magazine';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f8fafc","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1e293b","titleSize":"22px","titleFontWeight":800,"titleBackground":"#fff","titlePadding":"18px","titleBorderRadius":"12px","titleBorder":"1px solid #e2e8f0","titleMarginBottom":"20px","metaColor":"#64748b","metaBorder":"#e2e8f0","bodyColor":"#334155","bodySize":"14px","bodyLine":1.75,"headingColor":"#0f172a","headingSize":"15px","headingFontWeight":700,"headingBackground":"#fff","headingPadding":"8px 12px","headingBorderRadius":"8px","headingBorder":"1px solid #e2e8f0","calloutVariant":"card","calloutBg":"#fff","calloutColor":"#334155","calloutBorderRadius":"8px","calloutShadow":"0 2px 8px rgba(0,0,0,0.06)"}' WHERE template_key = 'card';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f8fbfa","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1a1a1a","titleSize":"24px","titleFontWeight":800,"titleIcon":"✅","titleBackground":"#f0faf4","titlePadding":"12px 16px","titleBorderRadius":"12px","titleBorder":"1px solid #d9e8e0","metaColor":"#527a6b","metaBorder":"#d9e8e0","bodyColor":"#2d3436","bodySize":"14px","bodyLine":1.85,"headingColor":"#52b788","headingSize":"16px","headingFontWeight":700,"headingBorder":"3px solid #52b788","headingPl":10,"calloutVariant":"checklist","calloutBg":"#f0faf4","calloutColor":"#2d3436","calloutBorderRadius":"6px"}' WHERE template_key = 'checklist';
UPDATE a_export_template SET visual_style_json = '{"bg":"#0d1117","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#00ff88","titleSize":"26px","titleFontWeight":900,"titleTextShadow":"0 0 12px rgba(0,255,136,0.45)","titleBackground":"linear-gradient(180deg, #161b22 0%, #0d1117 100%)","titlePadding":"16px","titleBorderRadius":"8px","titleBorder":"1px solid #30363d","metaColor":"#8899aa","metaBorder":"#30363d","bodyColor":"#e0e0e0","bodySize":"14px","bodyLine":1.85,"headingColor":"#00ff88","headingSize":"16px","headingFontWeight":700,"headingBorder":"3px solid #00ff88","headingPl":10,"headingTextShadow":"0 0 8px rgba(0,255,136,0.35)","calloutBg":"#161b22","calloutBorder":"1px solid #00ff88","calloutColor":"#00ff88","calloutBorderRadius":"6px","calloutShadow":"0 0 12px rgba(0,255,136,0.15)"}' WHERE template_key = 'dark';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1f2937","titleSize":"26px","titleFontWeight":500,"titleLetterSpacing":"0.02em","titleLineHeight":1.3,"titleBorderBottom":"1px solid #e5e7eb","titleMarginBottom":"16px","metaColor":"#6b7280","metaBorder":"#e5e7eb","bodyColor":"#374151","bodySize":"15px","bodyLine":1.9,"headingColor":"#1f2937","headingSize":"15px","headingFontWeight":600,"headingBorderBottom":"1px solid #e5e7eb","calloutBg":"#f9fafb","calloutBorder":"1px solid #e5e7eb","calloutColor":"#6b7280"}' WHERE template_key = 'wechat-minimal';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f8fbfa","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","titleFontWeight":700,"titleBackground":"#f0faf4","titlePadding":"12px 16px","titleBorderRadius":"16px","titleBorder":"1px solid #d9e8e0","metaColor":"#527a6b","metaBorder":"#d9e8e0","bodyColor":"#2d3436","bodySize":"14px","bodyLine":1.8,"headingColor":"#52b788","headingSize":"14px","headingFontWeight":700,"headingBackground":"#f0faf4","headingPadding":"6px 12px","headingBorderRadius":"12px","calloutVariant":"pill","calloutBg":"#f0faf4","calloutColor":"#52b788"}' WHERE template_key = 'wechat-dialogue';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f5f5f0","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#1b4332","titleSize":"26px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":700,"titleIcon":"🌿","titleBackground":"#fff","titlePadding":"16px","titleBorderRadius":"8px","titleBorder":"1px solid #d4a574","metaColor":"#52796f","metaBorder":"#d4a574","bodyColor":"#1b4332","bodySize":"15px","bodyLine":1.85,"headingColor":"#52796f","headingSize":"16px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingFontWeight":700,"headingBorder":"4px solid #52796f","headingPl":10,"calloutBg":"#e8f0e8","calloutBorder":"3px solid #52796f","calloutColor":"#1b4332"}' WHERE template_key = 'wechat-brand';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#fff","titleSize":"24px","titleFontWeight":900,"titleIcon":"📊","titleBackground":"#1a1a2e","titlePadding":"14px 18px","titleBorderRadius":"8px","metaColor":"#2b7ae8","metaBorder":"#d6e8f7","metaBackground":"#f0f7ff","metaPadding":"4px 10px","metaBorderRadius":"4px","bodyColor":"#1a1a2e","bodySize":"14px","bodyLine":1.75,"headingColor":"#2b7ae8","headingSize":"15px","headingFontWeight":700,"headingBackground":"#f0f7ff","headingPadding":"6px 10px","headingBorderRadius":"6px","calloutVariant":"card","calloutBg":"#fff","calloutColor":"#1a1a2e","calloutBorderRadius":"8px","calloutShadow":"0 2px 8px rgba(0,0,0,0.08)"}' WHERE template_key = 'wechat-infographic';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#ff006e","titleSize":"24px","titleFontWeight":900,"titleIcon":"🛍️","titleBackground":"#fff0f7","titlePadding":"12px 16px","titleBorderRadius":"12px","titleBorder":"2px solid #ff006e","metaColor":"#4a4a6a","metaBorder":"#ffd6e7","bodyColor":"#4a4a6a","bodySize":"14px","bodyLine":1.8,"headingColor":"#ff006e","headingSize":"15px","headingFontWeight":800,"headingBorder":"3px solid #ff006e","headingPl":10,"calloutVariant":"checklist","calloutBg":"#fff0f7","calloutColor":"#ff006e","calloutBorderRadius":"8px"}' WHERE template_key = 'xiaohongshu-list';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff9f5","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#e17055","titleSize":"24px","titleFontWeight":800,"titleIcon":"⭐","titleBackground":"#fff","titlePadding":"12px 16px","titleBorderRadius":"12px","titleBorder":"1px solid #fab1a0","metaColor":"#e17055","metaBorder":"#fab1a0","metaBackground":"#fff0e8","metaPadding":"4px 12px","metaBorderRadius":"999px","bodyColor":"#2d3436","bodySize":"14px","bodyLine":1.8,"headingColor":"#e17055","headingSize":"15px","headingFontWeight":700,"headingBorderBottom":"2px solid #fab1a0","calloutBg":"#fff0e8","calloutBorder":"3px solid #e17055","calloutColor":"#2d3436"}' WHERE template_key = 'xiaohongshu-review';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#5b8c85","titleSize":"24px","titleFontWeight":800,"titleIcon":"📝","titleBorderBottom":"3px solid #f4a6b3","titleMarginBottom":"18px","metaColor":"#a0aec0","metaBorder":"#f4a6b3","bodyColor":"#4a5568","bodySize":"14px","bodyLine":1.8,"headingColor":"#5b8c85","headingSize":"15px","headingFontWeight":700,"headingBorderBottom":"2px solid #f4a6b3","calloutVariant":"pill","calloutBg":"#fff5f7","calloutColor":"#f4a6b3"}' WHERE template_key = 'xiaohongshu-tutorial';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fafafa","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#1a1a1a","titleSize":"24px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":400,"titleAlign":"center","titleBackground":"linear-gradient(180deg, #f5f5f5 0%, #fff 100%)","titlePadding":"20px","titleBorderRadius":"16px","titleBorder":"1px solid #e5e5e5","metaColor":"#c23a30","metaBorder":"#e5e5e5","metaAlign":"center","bodyColor":"#1a1a1a","bodySize":"14px","bodyLine":1.9,"headingColor":"#c23a30","headingSize":"15px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingAlign":"center","headingBorderBottom":"1px solid #e5e5e5","calloutBg":"#f5f5f5","calloutBorder":"1px solid #e5e5e5","calloutColor":"#1a1a1a","calloutBorderRadius":"8px"}' WHERE template_key = 'xiaohongshu-emotion';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f5f5f5","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1a1a1a","titleSize":"26px","titleFontWeight":900,"titleBorderBottom":"3px solid #1a1a1a","titleMarginBottom":"16px","metaColor":"#fff","metaBackground":"#595959","metaPadding":"4px 10px","metaBorderRadius":"4px","bodyColor":"#4a4a4a","bodySize":"15px","bodyLine":1.9,"headingColor":"#984807","headingSize":"17px","headingFontWeight":800,"headingBorder":"4px solid #984807","headingPl":10,"calloutBg":"#f0f0f0","calloutBorder":"3px solid #984807","calloutColor":"#4a4a4a"}' WHERE template_key = 'toutiao-news';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fdf8f3","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#3d3229","titleSize":"24px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":700,"titleBorderBottom":"2px solid #b85c38","titleMarginBottom":"18px","metaColor":"#7d7067","metaBorder":"#e8dccb","bodyColor":"#3d3229","bodySize":"15px","bodyLine":1.85,"headingColor":"#b85c38","headingSize":"16px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingFontWeight":700,"headingBorderBottom":"1px solid #d4a373","calloutBg":"#f5ebe0","calloutBorder":"3px solid #b85c38","calloutColor":"#3d3229"}' WHERE template_key = 'toutiao-depth';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#fff","titleSize":"26px","titleFontWeight":900,"titleIcon":"🔥","titleBackground":"linear-gradient(135deg, #ff006e 0%, #fb5607 100%)","titlePadding":"16px","titleBorderRadius":"12px","titleTextShadow":"0 1px 2px rgba(0,0,0,0.2)","metaColor":"#ff006e","metaBorder":"#ffd6e7","metaBackground":"#fff0f7","metaPadding":"4px 10px","metaBorderRadius":"4px","bodyColor":"#4a4a6a","bodySize":"15px","bodyLine":1.9,"headingColor":"#ff006e","headingSize":"17px","headingFontWeight":800,"headingBorder":"4px solid #ff006e","headingPl":10,"calloutVariant":"cta","calloutBg":"#fff0f7","calloutColor":"#ff006e","calloutBorderRadius":"6px"}' WHERE template_key = 'toutiao-hot';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#2b7ae8","titleSize":"24px","titleFontWeight":800,"titleIcon":"❓","titleBackground":"#f0f7ff","titlePadding":"12px 16px","titleBorderRadius":"10px","titleBorder":"1px solid #d6e8f7","metaColor":"#8b9aaf","metaBorder":"#d6e8f7","bodyColor":"#1a1a2e","bodySize":"14px","bodyLine":1.8,"headingColor":"#2b7ae8","headingSize":"16px","headingFontWeight":700,"headingBorder":"4px solid #2b7ae8","headingPl":10,"calloutBg":"#f0f7ff","calloutBorder":"3px solid #2b7ae8","calloutColor":"#1a1a2e"}' WHERE template_key = 'toutiao-qa';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#fff","titleSize":"24px","titleFontWeight":900,"titleIcon":"⚛️","titleBackground":"#2b7ae8","titlePadding":"14px 18px","titleBorderRadius":"8px","metaColor":"#2b7ae8","metaBorder":"#d6e8f7","metaBackground":"#f0f7ff","metaPadding":"4px 10px","metaBorderRadius":"4px","bodyColor":"#1a1a2e","bodySize":"14px","bodyLine":1.85,"headingColor":"#2b7ae8","headingSize":"16px","headingFontWeight":700,"headingBorder":"4px solid #2b7ae8","headingPl":10,"calloutVariant":"card","calloutBg":"#fff","calloutColor":"#2b7ae8","calloutBorderRadius":"8px","calloutShadow":"0 2px 8px rgba(43,122,232,0.08)"}' WHERE template_key = 'baijiahao-science';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fdf8f3","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#3d3229","titleSize":"24px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":700,"titleBackground":"#f5ebe0","titlePadding":"14px","titleBorderRadius":"6px","titleBorder":"1px solid #d4a373","metaColor":"#7d7067","metaBorder":"#d4a373","bodyColor":"#3d3229","bodySize":"15px","bodyLine":1.9,"headingColor":"#b85c38","headingSize":"16px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingFontWeight":700,"headingBorderBottom":"1px solid #d4a373","calloutBg":"#f5ebe0","calloutBorder":"3px solid #b85c38","calloutColor":"#3d3229"}' WHERE template_key = 'baijiahao-history';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f8fbfa","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1a1a1a","titleSize":"24px","titleFontWeight":800,"titleIcon":"💡","titleBackground":"#f0faf4","titlePadding":"12px 16px","titleBorderRadius":"10px","titleBorder":"1px solid #d9e8e0","metaColor":"#527a6b","metaBorder":"#d9e8e0","bodyColor":"#2d3436","bodySize":"14px","bodyLine":1.75,"headingColor":"#52b788","headingSize":"15px","headingFontWeight":700,"headingBackground":"#f0faf4","headingPadding":"6px 10px","headingBorderRadius":"6px","calloutVariant":"card","calloutBg":"#fff","calloutColor":"#52b788","calloutBorderRadius":"8px","calloutShadow":"0 2px 8px rgba(82,183,136,0.08)"}' WHERE template_key = 'baijiahao-guide';
UPDATE a_export_template SET visual_style_json = '{"bg":"#f5f5f5","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#fff","titleSize":"26px","titleFontWeight":900,"titleAlign":"center","titleBackground":"#1a1a1a","titlePadding":"18px","titleBorderRadius":"12px","titleTextShadow":"0 0 10px rgba(255,255,255,0.3)","metaColor":"#8b9aaf","metaBorder":"#d9d9d9","metaAlign":"center","bodyColor":"#1a1a1a","bodySize":"15px","bodyLine":1.75,"bodyAlign":"center","headingColor":"#1a1a1a","headingSize":"16px","headingFontWeight":800,"headingAlign":"center","headingBorderBottom":"2px solid #1a1a1a","calloutBg":"#1a1a1a","calloutBorder":"none","calloutColor":"#fff","calloutBorderRadius":"8px"}' WHERE template_key = 'douyin-graphic';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fafafa","font":"Georgia, \\"Songti SC\\", serif","titleColor":"#1a1a1a","titleSize":"24px","titleFontFamily":"Georgia, \\"Songti SC\\", serif","titleFontWeight":400,"titleAlign":"center","titleBackground":"#fff","titlePadding":"20px","titleBorderRadius":"16px","titleBorder":"1px solid #e5e5e5","metaColor":"#c23a30","metaBorder":"#e5e5e5","metaAlign":"center","bodyColor":"#1a1a1a","bodySize":"16px","bodyLine":1.65,"bodyAlign":"center","headingColor":"#c23a30","headingSize":"16px","headingFontFamily":"Georgia, \\"Songti SC\\", serif","headingAlign":"center","calloutBg":"#f5f5f5","calloutBorder":"1px solid #e5e5e5","calloutColor":"#1a1a1a","calloutBorderRadius":"8px"}' WHERE template_key = 'douyin-quote';
UPDATE a_export_template SET visual_style_json = '{"bg":"#fff","font":"-apple-system, BlinkMacSystemFont, sans-serif","titleColor":"#1f2937","titleSize":"22px","titleFontWeight":700,"titleBackground":"#f9fafb","titlePadding":"12px 16px","titleBorderRadius":"0 10px 10px 0","titleBorder":"1px solid #e5e7eb","metaColor":"#6b7280","metaBorder":"#e5e7eb","bodyColor":"#374151","bodySize":"15px","bodyLine":1.85,"headingColor":"#e94560","headingSize":"16px","headingFontWeight":700,"headingBorder":"4px solid #e94560","headingPl":10,"calloutBg":"#fef2f3","calloutBorder":"3px solid #e94560","calloutColor":"#374151"}' WHERE template_key = 'zhihu-answer';
