-- 导出模板表（admin 管理、user 读取、pipeline 读签名）
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS a_export_template (
    id                  BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    template_key        VARCHAR(64)      NOT NULL COMMENT '模板标识，如 wechat / xiaohongshu-list',
    name                VARCHAR(128)     NOT NULL COMMENT '模板名称',
    platform            VARCHAR(32)      NOT NULL DEFAULT 'general' COMMENT '平台：wechat/xiaohongshu/toutiao/baijiahao/zhihu/douyin/general',
    description         VARCHAR(256)     NULL COMMENT '模板描述',
    bg_color            VARCHAR(16)      NOT NULL DEFAULT '#fff' COMMENT '卡片背景色',
    text_color          VARCHAR(16)      NOT NULL DEFAULT '#1a1a1a' COMMENT '卡片文字颜色',
    visual_style_json   JSON             NULL COMMENT '视觉预设 JSON（标题/小标题/正文/callout 样式）',
    signature_text      VARCHAR(128)     NULL COMMENT '签名文本，如 — 完 —',
    signature_position  VARCHAR(8)       NOT NULL DEFAULT 'end' COMMENT '签名位置：start/end',
    sort_order          INT              NOT NULL DEFAULT 0 COMMENT '排序',
    status              TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
    is_deleted          TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除：0-否，1-是',
    created_at          DATETIME(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by          BIGINT UNSIGNED  NOT NULL DEFAULT 0,
    updated_by          BIGINT UNSIGNED  NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_export_template_key (template_key),
    INDEX idx_export_template_platform (platform, status, is_deleted),
    INDEX idx_export_template_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='导出模板';

-- 种子数据：30 个模板
INSERT INTO a_export_template (template_key, name, platform, description, bg_color, text_color, visual_style_json, signature_text, signature_position, sort_order) VALUES
('wechat', '公众号标准模板', 'wechat', '简洁专业，适合深度长文', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.85","headingColor":"#1a1a1a","headingSize":"16px","headingBorder":"none","headingPl":"0","calloutBg":"#f6ffed","calloutBorder":"4px solid #07c160","calloutColor":"#262626"}',
 '— 完 —', 'end', 1),
('business', '商业财经模板', 'general', '专业严谨，适合商业分析', '#fff', '#003a8c',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#003a8c","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#d6e4ff","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.85","headingColor":"#003a8c","headingSize":"16px","headingBorder":"3px solid #003a8c","headingPl":"10","calloutBg":"#f0f5ff","calloutBorder":"3px solid #1677ff","calloutColor":"#003a8c"}',
 NULL, 'end', 2),
('marketing', '营销推广模板', 'general', '吸引眼球，适合营销内容', '#fff', '#cf1322',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#cf1322","titleSize":"24px","metaColor":"#8c8c8c","metaBorder":"#ffccc7","bodyColor":"#262626","bodySize":"15px","bodyLine":"1.85","headingColor":"#cf1322","headingSize":"17px","headingBorder":"3px solid #cf1322","headingPl":"10","calloutVariant":"cta"}',
 NULL, 'end', 3),
('academic', '学术论文模板', 'general', '严谨规范，适合学术写作', '#fafaf5', '#1a1a1a',
 '{"bg":"#fafaf5","font":"Georgia, \\\"Songti SC\\\", serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#d9d9d9","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.9","headingColor":"#1a1a1a","headingSize":"16px","headingBorder":"none","headingPl":"0","calloutBg":"#f5f5f0","calloutBorder":"none","calloutColor":"#595959","numbered":true}',
 NULL, 'end', 4),
('toutiao', '头条号标准模板', 'toutiao', '算法友好，适合热点资讯', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"24px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#222","bodySize":"15px","bodyLine":"1.9","headingColor":"#ff6600","headingSize":"17px","headingBorder":"4px solid #ff6600","headingPl":"10","calloutBg":"#fff7e6","calloutBorder":"3px solid #ff6600","calloutColor":"#262626"}',
 '（本文由爱创作生成）', 'end', 5),
('xiaohongshu', '小红书爆款模板', 'xiaohongshu', '种草安利，适合小红书风格', '#fff', '#ff2442',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#ff2442","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#ffd1d9","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.8","headingColor":"#ff2442","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutVariant":"pill"}',
 '#小红书 #爱创作', 'end', 6),
('baijiahao', '百家号模板', 'baijiahao', '多平台分发，适合资讯类', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#bae0ff","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.85","headingColor":"#1677ff","headingSize":"16px","headingBorder":"none","headingPl":"0","headingBorderBottom":"2px solid #1677ff","calloutBg":"#e6f4ff","calloutBorder":"3px solid #1677ff","calloutColor":"#1677ff"}',
 '—— 来自爱创作 ——', 'end', 7),
('story', '故事叙事模板', 'general', '沉浸叙事，适合故事类内容', '#faf5ef', '#8b5e34',
 '{"bg":"#faf5ef","font":"Georgia, \\\"Songti SC\\\", serif","titleColor":"#8b5e34","titleSize":"22px","metaColor":"#a89378","metaBorder":"#e8dccb","bodyColor":"#3a2e22","bodySize":"15px","bodyLine":"1.95","headingColor":"#8b5e34","headingSize":"16px","headingBorder":"3px solid #d4a373","headingPl":"10","calloutBg":"#f0e6d8","calloutBorder":"none","calloutColor":"#8b5e34"}',
 NULL, 'end', 8),
('magazine', '杂志风模板', 'general', '精致排版，适合生活方式', '#fafafa', '#1a1a1a',
 '{"bg":"#fafafa","font":"Georgia, \\\"Songti SC\\\", serif","titleColor":"#1a1a1a","titleSize":"26px","titleAlign":"center","metaColor":"#8c8c8c","metaBorder":"#d9d9d9","metaAlign":"center","bodyColor":"#595959","bodySize":"14px","bodyLine":"1.95","bodyAlign":"center","headingColor":"#1a1a1a","headingSize":"17px","headingBorder":"none","headingPl":"0","headingAlign":"center","calloutBg":"#f5f5f5","calloutBorder":"none","calloutColor":"#262626"}',
 NULL, 'end', 9),
('card', '卡片式模板', 'general', '模块化展示，信息清晰', '#f5f5f5', '#1a1a1a',
 '{"bg":"#f5f5f5","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"20px","metaColor":"#8c8c8c","metaBorder":"#e8e8e8","bodyColor":"#262626","bodySize":"13px","bodyLine":"1.7","headingColor":"#07c160","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutVariant":"card"}',
 NULL, 'end', 10),
('checklist', '清单攻略模板', 'general', '步骤清晰，适合教程攻略', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.85","headingColor":"#07c160","headingSize":"16px","headingBorder":"none","headingPl":"0","calloutVariant":"checklist"}',
 NULL, 'end', 11),
('dark', '深色模式模板', 'general', '科技感强，适合技术内容', '#1a1a1a', '#fff',
 '{"bg":"#1a1a1a","font":"-apple-system, sans-serif","titleColor":"#fff","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#333","bodyColor":"#d9d9d9","bodySize":"14px","bodyLine":"1.85","headingColor":"#95de64","headingSize":"16px","headingBorder":"3px solid #95de64","headingPl":"10","calloutBg":"#262626","calloutBorder":"none","calloutColor":"#95de64"}',
 NULL, 'end', 12),
('wechat-minimal', '公众号简约模板', 'wechat', '简约留白，适合文艺内容', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#262626","bodySize":"15px","bodyLine":"1.9","headingColor":"#1a1a1a","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutBg":"#fafafa","calloutBorder":"1px solid #e8e8e8","calloutColor":"#595959"}',
 '— 完 —', 'end', 13),
('wechat-dialogue', '公众号对话模板', 'wechat', '对话形式，适合访谈采访', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"20px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.8","headingColor":"#07c160","headingSize":"14px","headingBorder":"none","headingPl":"0","calloutVariant":"pill"}',
 '— 完 —', 'end', 14),
('wechat-brand', '品牌故事模板', 'wechat', '品牌调性，适合企业宣传', '#fff', '#07c160',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#07c160","titleSize":"24px","metaColor":"#8c8c8c","metaBorder":"#d9f7be","bodyColor":"#262626","bodySize":"15px","bodyLine":"1.85","headingColor":"#07c160","headingSize":"16px","headingBorder":"4px solid #07c160","headingPl":"10","calloutBg":"#f6ffed","calloutBorder":"3px solid #07c160","calloutColor":"#07c160"}',
 '— 完 —', 'end', 15),
('wechat-infographic', '信息图模板', 'wechat', '数据可视化，适合信息图解', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.75","headingColor":"#07c160","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutVariant":"card"}',
 '— 完 —', 'end', 16),
('xiaohongshu-list', '小红书清单模板', 'xiaohongshu', '清单形式，适合好物推荐', '#fff', '#ff2442',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#ff2442","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#ffd1d9","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.8","headingColor":"#ff2442","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutVariant":"checklist"}',
 '#小红书 #爱创作', 'end', 17),
('xiaohongshu-review', '小红书测评模板', 'xiaohongshu', '测评对比，适合产品体验', '#fff', '#ff2442',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#ff2442","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#ffd1d9","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.8","headingColor":"#ff6600","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutBg":"#fff7e6","calloutBorder":"3px solid #ff6600","calloutColor":"#262626"}',
 '#小红书 #爱创作', 'end', 18),
('xiaohongshu-tutorial', '小红书教程模板', 'xiaohongshu', '步骤详细，适合教程分享', '#fff', '#ff2442',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#ff2442","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#ffd1d9","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.8","headingColor":"#ff2442","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutVariant":"pill"}',
 '#小红书 #爱创作', 'end', 19),
('xiaohongshu-emotion', '小红书情感模板', 'xiaohongshu', '情感共鸣，适合成长分享', '#fff', '#ff2442',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#ff2442","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#ffd1d9","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.9","headingColor":"#ff2442","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutBg":"#fff0f3","calloutBorder":"1px solid #ffd1d9","calloutColor":"#262626"}',
 '#小红书 #爱创作', 'end', 20),
('toutiao-news', '头条新闻模板', 'toutiao', '新闻体，适合资讯报道', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"24px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#222","bodySize":"15px","bodyLine":"1.9","headingColor":"#ff6600","headingSize":"17px","headingBorder":"4px solid #ff6600","headingPl":"10","calloutBg":"#fff7e6","calloutBorder":"3px solid #ff6600","calloutColor":"#262626"}',
 '（本文由爱创作生成）', 'end', 21),
('toutiao-depth', '头条深度模板', 'toutiao', '深度分析，适合专题报道', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#222","bodySize":"15px","bodyLine":"1.85","headingColor":"#1a1a1a","headingSize":"16px","headingBorder":"none","headingPl":"0","headingBorderBottom":"2px solid #ff6600","calloutBg":"#fff7e6","calloutBorder":"3px solid #ff6600","calloutColor":"#262626"}',
 '（本文由爱创作生成）', 'end', 22),
('toutiao-hot', '头条热点模板', 'toutiao', '热点追踪，适合爆款文章', '#fff', '#ff6600',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#ff6600","titleSize":"24px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#222","bodySize":"15px","bodyLine":"1.9","headingColor":"#ff6600","headingSize":"17px","headingBorder":"4px solid #ff6600","headingPl":"10","calloutVariant":"cta"}',
 '（本文由爱创作生成）', 'end', 23),
('toutiao-qa', '头条问答模板', 'toutiao', '问答形式，适合知识解答', '#fff', '#ff6600',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#ff6600","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#222","bodySize":"14px","bodyLine":"1.8","headingColor":"#ff6600","headingSize":"16px","headingBorder":"4px solid #ff6600","headingPl":"10","calloutBg":"#fff7e6","calloutBorder":"3px solid #ff6600","calloutColor":"#262626"}',
 '（本文由爱创作生成）', 'end', 24),
('baijiahao-science', '百家号科普模板', 'baijiahao', '知识科普，适合科学讲解', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#bae0ff","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.85","headingColor":"#1677ff","headingSize":"16px","headingBorder":"4px solid #1677ff","headingPl":"10","calloutBg":"#e6f4ff","calloutBorder":"3px solid #1677ff","calloutColor":"#1677ff"}',
 '—— 来自爱创作 ——', 'end', 25),
('baijiahao-history', '百家号历史模板', 'baijiahao', '人文历史，适合故事讲述', '#fafafa', '#1a1a1a',
 '{"bg":"#fafafa","font":"Georgia, \\\"Songti SC\\\", serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#d9d9d9","bodyColor":"#262626","bodySize":"15px","bodyLine":"1.9","headingColor":"#1677ff","headingSize":"16px","headingBorder":"none","headingPl":"0","headingBorderBottom":"1px solid #1677ff","calloutBg":"#e6f4ff","calloutBorder":"3px solid #1677ff","calloutColor":"#1677ff"}',
 '—— 来自爱创作 ——', 'end', 26),
('baijiahao-guide', '百家号攻略模板', 'baijiahao', '实用攻略，适合生活指南', '#fff', '#1677ff',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1677ff","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#bae0ff","bodyColor":"#262626","bodySize":"14px","bodyLine":"1.75","headingColor":"#1677ff","headingSize":"15px","headingBorder":"none","headingPl":"0","calloutVariant":"card"}',
 '—— 来自爱创作 ——', 'end', 27),
('douyin-graphic', '抖音图文金句模板', 'douyin', '金句卡片，适合短视频配套', '#f5f5f5', '#1a1a1a',
 '{"bg":"#f5f5f5","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"26px","titleAlign":"center","metaColor":"#8c8c8c","metaBorder":"#d9d9d9","metaAlign":"center","bodyColor":"#1a1a1a","bodySize":"15px","bodyLine":"1.75","bodyAlign":"center","headingColor":"#1a1a1a","headingSize":"16px","headingBorder":"none","headingPl":"0","headingAlign":"center","calloutBg":"#fff","calloutBorder":"1px solid #d9d9d9","calloutColor":"#1a1a1a"}',
 NULL, 'end', 28),
('douyin-quote', '抖音图文语录模板', 'douyin', '语录风格，适合励志文案', '#f5f5f5', '#1a1a1a',
 '{"bg":"#f5f5f5","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"24px","titleAlign":"center","metaColor":"#8c8c8c","metaBorder":"#d9d9d9","metaAlign":"center","bodyColor":"#1a1a1a","bodySize":"16px","bodyLine":"1.65","bodyAlign":"center","headingColor":"#1a1a1a","headingSize":"16px","headingBorder":"none","headingPl":"0","headingAlign":"center","calloutBg":"#1a1a1a","calloutBorder":"none","calloutColor":"#fff"}',
 NULL, 'end', 29),
('zhihu-answer', '知乎回答模板', 'zhihu', '专业回答，适合知识分享', '#fff', '#1a1a1a',
 '{"bg":"#fff","font":"-apple-system, sans-serif","titleColor":"#1a1a1a","titleSize":"22px","metaColor":"#8c8c8c","metaBorder":"#eee","bodyColor":"#262626","bodySize":"15px","bodyLine":"1.85","headingColor":"#0066ff","headingSize":"16px","headingBorder":"4px solid #0066ff","headingPl":"10","calloutBg":"#f0f5ff","calloutBorder":"3px solid #0066ff","calloutColor":"#0066ff"}',
 '> 本文由爱创作 AI 生成。', 'start', 30);
