SET NAMES utf8mb4;

-- ============================================================
-- 2026-08-27: 丰富导出模板视觉样式
--   1) 补充 a_export_template_param 参数定义，让管理端可编辑新字段
--   2) 重写 30 个模板 visual_style_json，让标题、Meta、小标题、
--      高亮块风格差异化（杂志/卡片/深色/对话/情感/热点等）
-- ============================================================

-- 1) 新增参数定义（已存在则忽略）
INSERT IGNORE INTO a_export_template_param (param_key, display_label, field_type, group_label, default_value, options_json, sort_order) VALUES
    ('titleIcon', '标题图标前缀', 'text', '标题', NULL, NULL, 35),
    ('titleFontFamily', '标题字体', 'text', '标题', NULL, NULL, 40),
    ('titleFontStyle', '标题字形', 'select', '标题', 'normal', '["normal","italic"]', 45),
    ('titleFontWeight', '标题字重', 'number', '标题', '700', NULL, 50),
    ('titleLetterSpacing', '标题字间距', 'text', '标题', NULL, NULL, 55),
    ('titleLineHeight', '标题行高', 'number', '标题', '1.4', NULL, 60),
    ('titleTextShadow', '标题文字阴影', 'text', '标题', NULL, NULL, 65),
    ('titleBackground', '标题背景', 'text', '标题', NULL, NULL, 70),
    ('titlePadding', '标题内边距', 'text', '标题', NULL, NULL, 75),
    ('titleBorderRadius', '标题圆角', 'text', '标题', NULL, NULL, 80),
    ('titleBorder', '标题边框', 'text', '标题', NULL, NULL, 85),
    ('titleTransform', '标题大小写转换', 'select', '标题', 'none', '["none","uppercase","capitalize"]', 90),
    ('titleMarginBottom', '标题下边距', 'text', '标题', NULL, NULL, 95),
    ('metaBackground', 'Meta 背景色', 'color', 'Meta', NULL, NULL, 40),
    ('metaPadding', 'Meta 内边距', 'text', 'Meta', NULL, NULL, 50),
    ('metaBorderRadius', 'Meta 圆角', 'text', 'Meta', NULL, NULL, 60),
    ('headingFontFamily', '小标题字体', 'text', '小标题', NULL, NULL, 80),
    ('headingFontWeight', '小标题字重', 'number', '小标题', '600', NULL, 90),
    ('headingLetterSpacing', '小标题字间距', 'text', '小标题', NULL, NULL, 100),
    ('headingTextTransform', '小标题大小写转换', 'select', '小标题', 'none', '["none","uppercase","capitalize"]', 110),
    ('headingBackground', '小标题背景', 'color', '小标题', NULL, NULL, 120),
    ('headingPadding', '小标题内边距', 'text', '小标题', NULL, NULL, 130),
    ('headingBorderRadius', '小标题圆角', 'text', '小标题', NULL, NULL, 140),
    ('headingMargin', '小标题外边距', 'text', '小标题', NULL, NULL, 150),
    ('calloutBorderRadius', '高亮块圆角', 'text', '高亮块', '0 6px 6px 0', NULL, 50),
    ('calloutShadow', '高亮块阴影', 'text', '高亮块', NULL, NULL, 60);

-- 2) 更新 30 个模板视觉样式
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "24px", "titleFontWeight": 700, "titleLetterSpacing": "-0.01em", "titleLineHeight": 1.35, "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#262626", "bodySize": "15px", "bodyLine": 1.85, "headingColor": "#07c160", "headingSize": "17px", "headingBorder": "4px solid #07c160", "headingPl": 10, "calloutBg": "#f6ffed", "calloutBorder": "4px solid #07c160", "calloutColor": "#262626"}' WHERE template_key = 'wechat';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#003a8c", "titleSize": "24px", "titleFontWeight": 800, "titleBackground": "#f0f5ff", "titlePadding": "14px 16px", "titleBorderRadius": "6px", "titleBorder": "1px solid #d6e4ff", "metaColor": "#595959", "metaBorder": "#d6e4ff", "metaBackground": "#f0f5ff", "metaPadding": "4px 10px", "metaBorderRadius": "4px", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.85, "headingColor": "#003a8c", "headingSize": "16px", "headingBorder": "3px solid #003a8c", "headingPl": 10, "headingBackground": "#f0f5ff", "headingPadding": "6px 10px", "headingBorderRadius": "4px", "calloutBg": "#f0f5ff", "calloutBorder": "3px solid #1677ff", "calloutColor": "#003a8c"}' WHERE template_key = 'business';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#cf1322", "titleSize": "26px", "titleFontWeight": 900, "titleLetterSpacing": "0.02em", "titleBackground": "linear-gradient(135deg, #fff1f0 0%, #fff7e6 100%)", "titlePadding": "16px", "titleBorderRadius": "10px", "titleBorder": "2px solid #ffccc7", "metaColor": "#8c8c8c", "metaBorder": "#ffccc7", "bodyColor": "#262626", "bodySize": "15px", "bodyLine": 1.85, "headingColor": "#cf1322", "headingSize": "17px", "headingBorder": "3px solid #cf1322", "headingPl": 10, "headingFontWeight": 700, "calloutVariant": "cta", "calloutBg": "#fff", "calloutColor": "#cf1322", "calloutBorderRadius": "6px"}' WHERE template_key = 'marketing';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fafaf5", "font": "Georgia, \\"Songti SC\\", serif", "titleColor": "#1a1a1a", "titleSize": "24px", "titleFontFamily": "Georgia, \\"Songti SC\\", serif", "titleFontWeight": 400, "titleLetterSpacing": "0.02em", "titleAlign": "center", "metaColor": "#8c8c8c", "metaBorder": "#d9d9d9", "metaAlign": "center", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.9, "bodyAlign": "justify", "headingColor": "#1a1a1a", "headingSize": "16px", "headingFontFamily": "Georgia, \\"Songti SC\\", serif", "headingBorderBottom": "1px solid #d9d9d9", "headingFontWeight": 700, "numbered": true, "calloutBg": "#f5f5f0", "calloutBorder": "none", "calloutColor": "#595959"}' WHERE template_key = 'academic';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "26px", "titleFontWeight": 800, "titleBorderBottom": "4px solid #ff6600", "titleMarginBottom": "16px", "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#222", "bodySize": "15px", "bodyLine": 1.9, "headingColor": "#ff6600", "headingSize": "17px", "headingBorder": "4px solid #ff6600", "headingPl": 10, "calloutBg": "#fff7e6", "calloutBorder": "3px solid #ff6600", "calloutColor": "#262626"}' WHERE template_key = 'toutiao';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#ff2442", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "🌸", "titleBackground": "#fff0f3", "titlePadding": "12px 18px", "titleBorderRadius": "14px", "metaColor": "#8c8c8c", "metaBorder": "#ffd1d9", "metaBackground": "#fff0f3", "metaPadding": "4px 10px", "metaBorderRadius": "999px", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.8, "headingColor": "#ff2442", "headingSize": "15px", "headingBorderBottom": "2px solid #ffd1d9", "calloutVariant": "pill", "calloutBg": "#fff0f3", "calloutColor": "#ff2442"}' WHERE template_key = 'xiaohongshu';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1677ff", "titleSize": "24px", "titleFontWeight": 800, "titleBackground": "#e6f4ff", "titlePadding": "12px 16px", "titleBorderRadius": "8px", "titleBorder": "1px solid #bae0ff", "metaColor": "#595959", "metaBorder": "#bae0ff", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.85, "headingColor": "#1677ff", "headingSize": "16px", "headingBorderBottom": "2px solid #1677ff", "headingFontWeight": 700, "calloutBg": "#e6f4ff", "calloutBorder": "3px solid #1677ff", "calloutColor": "#1677ff"}' WHERE template_key = 'baijiahao';
UPDATE a_export_template SET visual_style_json = '{"bg": "#faf5ef", "font": "Georgia, \\"Songti SC\\", serif", "titleColor": "#8b5e34", "titleSize": "24px", "titleFontFamily": "Georgia, \\"Songti SC\\", serif", "titleFontWeight": 400, "titleFontStyle": "italic", "titleBorderBottom": "2px solid #d4a373", "titleMarginBottom": "20px", "metaColor": "#a89378", "metaBorder": "#e8dccb", "metaAlign": "center", "bodyColor": "#3a2e22", "bodySize": "15px", "bodyLine": 1.95, "headingColor": "#8b5e34", "headingSize": "16px", "headingFontFamily": "Georgia, \\"Songti SC\\", serif", "headingBorderBottom": "1px solid #d4a373", "calloutBg": "#f0e6d8", "calloutBorder": "none", "calloutColor": "#8b5e34"}' WHERE template_key = 'story';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fafafa", "font": "Georgia, \\"Songti SC\\", serif", "titleColor": "#1a1a1a", "titleSize": "28px", "titleFontFamily": "Georgia, \\"Songti SC\\", serif", "titleFontWeight": 400, "titleAlign": "center", "titleLetterSpacing": "0.04em", "titleBackground": "#fff", "titlePadding": "16px", "titleBorderRadius": "0", "titleBorder": "1px solid #d9d9d9", "titleMarginBottom": "20px", "metaColor": "#8c8c8c", "metaBorder": "#d9d9d9", "metaAlign": "center", "bodyColor": "#595959", "bodySize": "14px", "bodyLine": 1.95, "bodyAlign": "center", "headingColor": "#1a1a1a", "headingSize": "17px", "headingFontFamily": "Georgia, \\"Songti SC\\", serif", "headingAlign": "center", "headingBorderBottom": "1px solid #d9d9d9", "calloutBg": "#f5f5f5", "calloutBorder": "none", "calloutColor": "#262626"}' WHERE template_key = 'magazine';
UPDATE a_export_template SET visual_style_json = '{"bg": "#f5f5f5", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "22px", "titleFontWeight": 700, "titleBackground": "#fff", "titlePadding": "18px", "titleBorderRadius": "12px", "titleBorder": "1px solid #e8e8e8", "titleMarginBottom": "20px", "metaColor": "#8c8c8c", "metaBorder": "#e8e8e8", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.75, "headingColor": "#07c160", "headingSize": "15px", "headingBackground": "#fff", "headingPadding": "8px 12px", "headingBorderRadius": "8px", "headingBorder": "1px solid #e8e8e8", "calloutVariant": "card", "calloutBg": "#fff", "calloutColor": "#262626", "calloutBorderRadius": "8px", "calloutShadow": "0 2px 8px rgba(0,0,0,0.06)"}' WHERE template_key = 'card';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "✅", "titleBackground": "#f6ffed", "titlePadding": "12px 16px", "titleBorderRadius": "10px", "titleBorder": "1px solid #d9f7be", "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.85, "headingColor": "#07c160", "headingSize": "16px", "headingBorder": "3px solid #07c160", "headingPl": 10, "calloutVariant": "checklist", "calloutBg": "#f6ffed", "calloutColor": "#262626"}' WHERE template_key = 'checklist';
UPDATE a_export_template SET visual_style_json = '{"bg": "#1a1a1a", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#95de64", "titleSize": "26px", "titleFontWeight": 800, "titleTextShadow": "0 0 10px rgba(149,222,100,0.35)", "metaColor": "#8c8c8c", "metaBorder": "#333", "bodyColor": "#d9d9d9", "bodySize": "14px", "bodyLine": 1.85, "headingColor": "#95de64", "headingSize": "16px", "headingBorder": "3px solid #95de64", "headingPl": 10, "headingTextShadow": "0 0 6px rgba(149,222,100,0.25)", "calloutBg": "#262626", "calloutBorder": "none", "calloutColor": "#95de64"}' WHERE template_key = 'dark';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "26px", "titleFontWeight": 500, "titleLetterSpacing": "0.02em", "titleLineHeight": 1.3, "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#262626", "bodySize": "15px", "bodyLine": 1.9, "headingColor": "#1a1a1a", "headingSize": "15px", "headingFontWeight": 600, "headingBorderBottom": "1px solid #eee", "calloutBg": "#fafafa", "calloutBorder": "1px solid #e8e8e8", "calloutColor": "#595959"}' WHERE template_key = 'wechat-minimal';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "22px", "titleFontWeight": 600, "titleBackground": "#f6ffed", "titlePadding": "12px 16px", "titleBorderRadius": "16px", "titleBorder": "1px solid #d9f7be", "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.8, "headingColor": "#07c160", "headingSize": "14px", "headingBackground": "#f6ffed", "headingPadding": "6px 10px", "headingBorderRadius": "12px", "calloutVariant": "pill", "calloutBg": "#f6ffed", "calloutColor": "#07c160"}' WHERE template_key = 'wechat-dialogue';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#07c160", "titleSize": "26px", "titleFontWeight": 900, "titleIcon": "🌿", "titleBackground": "#f6ffed", "titlePadding": "14px 18px", "titleBorderRadius": "10px", "titleBorder": "1px solid #d9f7be", "metaColor": "#8c8c8c", "metaBorder": "#d9f7be", "bodyColor": "#262626", "bodySize": "15px", "bodyLine": 1.85, "headingColor": "#07c160", "headingSize": "16px", "headingBorder": "4px solid #07c160", "headingPl": 10, "calloutBg": "#f6ffed", "calloutBorder": "3px solid #07c160", "calloutColor": "#07c160"}' WHERE template_key = 'wechat-brand';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "📊", "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.75, "headingColor": "#07c160", "headingSize": "15px", "headingBackground": "#f6ffed", "headingPadding": "6px 10px", "headingBorderRadius": "6px", "calloutVariant": "card", "calloutBg": "#fff", "calloutColor": "#262626", "calloutBorderRadius": "8px"}' WHERE template_key = 'wechat-infographic';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#ff2442", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "🛍️", "titleBackground": "#fff0f3", "titlePadding": "12px 16px", "titleBorderRadius": "12px", "metaColor": "#8c8c8c", "metaBorder": "#ffd1d9", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.8, "headingColor": "#ff2442", "headingSize": "15px", "headingBorder": "3px solid #ff2442", "headingPl": 10, "calloutVariant": "checklist", "calloutBg": "#fff0f3", "calloutColor": "#ff2442"}' WHERE template_key = 'xiaohongshu-list';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#ff6600", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "⭐", "titleBackground": "#fff7e6", "titlePadding": "12px 16px", "titleBorderRadius": "12px", "metaColor": "#8c8c8c", "metaBorder": "#ffd1d9", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.8, "headingColor": "#ff6600", "headingSize": "15px", "headingBorderBottom": "2px solid #ff6600", "calloutBg": "#fff7e6", "calloutBorder": "3px solid #ff6600", "calloutColor": "#262626"}' WHERE template_key = 'xiaohongshu-review';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#ff2442", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "📝", "titleBorderBottom": "3px solid #ff2442", "titleMarginBottom": "18px", "metaColor": "#8c8c8c", "metaBorder": "#ffd1d9", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.8, "headingColor": "#ff2442", "headingSize": "15px", "headingBorderBottom": "2px solid #ffd1d9", "calloutVariant": "pill", "calloutBg": "#fff0f3", "calloutColor": "#ff2442"}' WHERE template_key = 'xiaohongshu-tutorial';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#ff2442", "titleSize": "24px", "titleFontWeight": 700, "titleAlign": "center", "titleBackground": "linear-gradient(180deg, #fff0f3 0%, #ffffff 100%)", "titlePadding": "20px", "titleBorderRadius": "16px", "titleBorder": "1px solid #ffd1d9", "metaColor": "#8c8c8c", "metaBorder": "#ffd1d9", "metaAlign": "center", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.9, "headingColor": "#ff2442", "headingSize": "15px", "headingAlign": "center", "headingBorderBottom": "1px solid #ffd1d9", "calloutBg": "#fff0f3", "calloutBorder": "1px solid #ffd1d9", "calloutColor": "#262626"}' WHERE template_key = 'xiaohongshu-emotion';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "26px", "titleFontWeight": 800, "titleBorderBottom": "3px solid #1a1a1a", "titleMarginBottom": "16px", "metaColor": "#fff", "metaBackground": "#595959", "metaPadding": "4px 10px", "metaBorderRadius": "4px", "bodyColor": "#222", "bodySize": "15px", "bodyLine": 1.9, "headingColor": "#ff6600", "headingSize": "17px", "headingBorder": "4px solid #ff6600", "headingPl": 10, "calloutBg": "#fff7e6", "calloutBorder": "3px solid #ff6600", "calloutColor": "#262626"}' WHERE template_key = 'toutiao-news';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "24px", "titleFontWeight": 800, "titleBorderBottom": "4px solid #ff6600", "titleMarginBottom": "18px", "metaColor": "#595959", "metaBorder": "#d9d9d9", "bodyColor": "#222", "bodySize": "15px", "bodyLine": 1.85, "headingColor": "#1a1a1a", "headingSize": "16px", "headingBorderBottom": "2px solid #ff6600", "headingFontWeight": 700, "calloutBg": "#fff7e6", "calloutBorder": "3px solid #ff6600", "calloutColor": "#262626"}' WHERE template_key = 'toutiao-depth';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#fff", "titleSize": "26px", "titleFontWeight": 900, "titleIcon": "🔥", "titleBackground": "linear-gradient(135deg, #ff6600 0%, #ff4d4f 100%)", "titlePadding": "16px", "titleBorderRadius": "12px", "titleTextShadow": "0 1px 2px rgba(0,0,0,0.2)", "metaColor": "#ff6600", "metaBorder": "#ffccc7", "metaBackground": "#fff7e6", "metaPadding": "4px 10px", "metaBorderRadius": "4px", "bodyColor": "#222", "bodySize": "15px", "bodyLine": 1.9, "headingColor": "#ff6600", "headingSize": "17px", "headingBorder": "4px solid #ff6600", "headingPl": 10, "calloutVariant": "cta", "calloutBg": "#fff7e6", "calloutColor": "#ff6600", "calloutBorderRadius": "6px"}' WHERE template_key = 'toutiao-hot';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#ff6600", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "❓", "titleBackground": "#fff7e6", "titlePadding": "12px 16px", "titleBorderRadius": "10px", "titleBorder": "1px solid #ffd8bf", "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#222", "bodySize": "14px", "bodyLine": 1.8, "headingColor": "#ff6600", "headingSize": "16px", "headingBorder": "4px solid #ff6600", "headingPl": 10, "calloutBg": "#fff7e6", "calloutBorder": "3px solid #ff6600", "calloutColor": "#262626"}' WHERE template_key = 'toutiao-qa';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1677ff", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "⚛️", "titleBackground": "#e6f4ff", "titlePadding": "12px 16px", "titleBorderRadius": "10px", "titleBorder": "1px solid #bae0ff", "metaColor": "#595959", "metaBorder": "#bae0ff", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.85, "headingColor": "#1677ff", "headingSize": "16px", "headingBorder": "4px solid #1677ff", "headingPl": 10, "calloutVariant": "card", "calloutBg": "#fff", "calloutColor": "#1677ff", "calloutBorderRadius": "8px"}' WHERE template_key = 'baijiahao-science';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fafafa", "font": "Georgia, \\"Songti SC\\", serif", "titleColor": "#1a1a1a", "titleSize": "24px", "titleFontFamily": "Georgia, \\"Songti SC\\", serif", "titleFontWeight": 700, "titleBackground": "#f5f0e6", "titlePadding": "14px", "titleBorderRadius": "6px", "titleBorder": "1px solid #e8dccb", "metaColor": "#8c8c8c", "metaBorder": "#d9d9d9", "bodyColor": "#262626", "bodySize": "15px", "bodyLine": 1.9, "headingColor": "#1677ff", "headingSize": "16px", "headingFontFamily": "Georgia, \\"Songti SC\\", serif", "headingBorderBottom": "1px solid #1677ff", "calloutBg": "#e6f4ff", "calloutBorder": "3px solid #1677ff", "calloutColor": "#1677ff"}' WHERE template_key = 'baijiahao-history';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1677ff", "titleSize": "24px", "titleFontWeight": 800, "titleIcon": "💡", "titleBackground": "#e6f4ff", "titlePadding": "12px 16px", "titleBorderRadius": "10px", "metaColor": "#595959", "metaBorder": "#bae0ff", "bodyColor": "#262626", "bodySize": "14px", "bodyLine": 1.75, "headingColor": "#1677ff", "headingSize": "15px", "headingBackground": "#e6f4ff", "headingPadding": "6px 10px", "headingBorderRadius": "6px", "calloutVariant": "card", "calloutBg": "#fff", "calloutColor": "#1677ff", "calloutBorderRadius": "8px"}' WHERE template_key = 'baijiahao-guide';
UPDATE a_export_template SET visual_style_json = '{"bg": "#f5f5f5", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#fff", "titleSize": "26px", "titleFontWeight": 900, "titleAlign": "center", "titleBackground": "#1a1a1a", "titlePadding": "18px", "titleBorderRadius": "12px", "titleTextShadow": "0 1px 3px rgba(0,0,0,0.3)", "metaColor": "#8c8c8c", "metaBorder": "#d9d9d9", "metaAlign": "center", "bodyColor": "#1a1a1a", "bodySize": "15px", "bodyLine": 1.75, "bodyAlign": "center", "headingColor": "#1a1a1a", "headingSize": "16px", "headingAlign": "center", "headingBorderBottom": "2px solid #1a1a1a", "calloutBg": "#fff", "calloutBorder": "1px solid #d9d9d9", "calloutColor": "#1a1a1a"}' WHERE template_key = 'douyin-graphic';
UPDATE a_export_template SET visual_style_json = '{"bg": "#f5f5f5", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#fff", "titleSize": "24px", "titleFontWeight": 800, "titleAlign": "center", "titleBackground": "#1a1a1a", "titlePadding": "20px", "titleBorderRadius": "16px", "metaColor": "#8c8c8c", "metaBorder": "#d9d9d9", "metaAlign": "center", "bodyColor": "#1a1a1a", "bodySize": "16px", "bodyLine": 1.65, "bodyAlign": "center", "headingColor": "#1a1a1a", "headingSize": "16px", "headingAlign": "center", "calloutBg": "#1a1a1a", "calloutBorder": "none", "calloutColor": "#fff"}' WHERE template_key = 'douyin-quote';
UPDATE a_export_template SET visual_style_json = '{"bg": "#fff", "font": "-apple-system, BlinkMacSystemFont, sans-serif", "titleColor": "#1a1a1a", "titleSize": "22px", "titleFontWeight": 700, "titleBackground": "#f0f5ff", "titlePadding": "12px 16px", "titleBorderRadius": "0 10px 10px 0", "titleBorder": "1px solid #d6e4ff", "metaColor": "#8c8c8c", "metaBorder": "#eee", "bodyColor": "#262626", "bodySize": "15px", "bodyLine": 1.85, "headingColor": "#0066ff", "headingSize": "16px", "headingBorder": "4px solid #0066ff", "headingPl": 10, "calloutBg": "#f0f5ff", "calloutBorder": "3px solid #0066ff", "calloutColor": "#0066ff"}' WHERE template_key = 'zhihu-answer';
