SET NAMES utf8mb4;

-- 新增快手图文平台配置
INSERT INTO c_platform (
    platform_key,
    platform_name,
    description,
    recommend_words,
    trait,
    word_count_presets_json,
    sort_order,
    status,
    is_default,
    icon_url,
    tagline,
    content_form_json,
    monetization_json,
    threshold,
    best_for,
    reason,
    monetization_ease,
    time_to_income,
    income_range,
    difficulty
) VALUES (
    'kuaishou',
    '快手图文',
    '下沉市场大，老铁文化强，图文种草流量蓝海',
    500,
    '接地气口语化，强互动，适合生活化种草',
    JSON_ARRAY(
        JSON_OBJECT('count', 150, 'label', '封面金句'),
        JSON_OBJECT('count', 300, 'label', '短图文'),
        JSON_OBJECT('count', 500, 'label', '详细图文'),
        JSON_OBJECT('count', 800, 'label', '深度种草')
    ),
    55,
    1,
    0,
    NULL,
    '下沉市场流量蓝海，老铁信任度高，图文种草起号快',
    JSON_ARRAY('图文', '短视频', '直播'),
    JSON_ARRAY('广告分成', '带货', '直播打赏', '磁力聚星'),
    '0粉可带货，1000粉可接磁力聚星商单',
    '擅长生活化表达、愿意和粉丝高频互动的人',
    '老铁文化信任度高，带货转化好，图文内容竞争相对小',
    '容易',
    '1-3个月',
    '几千~几万/月',
    '低'
) ON DUPLICATE KEY UPDATE
    platform_name = VALUES(platform_name),
    description = VALUES(description),
    recommend_words = VALUES(recommend_words),
    trait = VALUES(trait),
    word_count_presets_json = VALUES(word_count_presets_json),
    sort_order = VALUES(sort_order),
    status = VALUES(status),
    is_default = VALUES(is_default),
    icon_url = VALUES(icon_url),
    tagline = VALUES(tagline),
    content_form_json = VALUES(content_form_json),
    monetization_json = VALUES(monetization_json),
    threshold = VALUES(threshold),
    best_for = VALUES(best_for),
    reason = VALUES(reason),
    monetization_ease = VALUES(monetization_ease),
    time_to_income = VALUES(time_to_income),
    income_range = VALUES(income_range),
    difficulty = VALUES(difficulty);
